apiVersion: apps/v1
kind: Deployment
metadata: { name: api }
spec:
  replicas: 2
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
      - name: api
        image: myapp:latest          # build & load next
        ports: [{ containerPort: 3000 }]
        env:
        - name: DATABASE_URL
          value: postgres://user:pass@db:5432/myapp
---
apiVersion: v1
kind: Service
metadata: { name: api }
spec:
  type: NodePort
  selector: { app: api }
  ports: [{ port: 3000, targetPort: 3000, nodePort: 30030 }]
---
# Add StatefulSet or Deployment + Service for 'db' similarly
